In [19]:
# Package imports
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.linear_model
import pandas as pd

from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split
#from planar_utils import plot_decision_boundary, sigmoid, load_planar_dataset, load_extra_datasets

##### Entrando com os dados

In [20]:
df = pd.read_csv('abalone_dataset.csv')

df.loc[(df['sex'] == 'M'), 'sex'] = 2
df.loc[(df['sex'] == 'F'), 'sex'] = 1
df.loc[(df['sex'] == 'I'), 'sex'] = 0

X = df.iloc[:, :8].values #Array 2D
y = df.iloc[:, 8].values

scalar = StandardScaler()
X = scalar.fit_transform(X)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1, random_state=42)

In [21]:
print(X.shape)

(3132, 8)


#### Modelo Sequencial de Redes Densas

In [22]:
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.initializers import HeNormal

def create_model():
    # Exemplo de modelo de classificação
    model = Sequential([
        Dense(16, activation='relu', input_shape=(8,), kernel_initializer= HeNormal(), kernel_regularizer=l2(0.001)),
        Dense(8, activation='relu', kernel_initializer= HeNormal(), kernel_regularizer=l2(0.001)),
        Dense(4, activation='softmax',kernel_initializer= HeNormal())  # Camada de saída para classificação
    ])

    optimizer = Adam(learning_rate=0.01)

    model.compile(
        loss='sparse_categorical_crossentropy',  # Função de perda para classificação
        optimizer=optimizer,
        metrics=['accuracy']  # Métricas para classificação
    )

    return model

In [23]:
# Treinar o modelo. Bom com eta = 0.01
model = create_model()
model.fit(X_train, y_train, epochs=60, batch_size=200, validation_data=(X_val, y_val), verbose=0)

# Avaliar o modelo
loss, mse = model.evaluate(X_val, y_val)
print(f'Loss: {loss:.4f}, Mean Squared Error: {mse:.4f}')

y_predNN = model.predict(X_val)
y_predNN = np.argmax(y_predNN, axis=1)

c:\Users\CarlosPessoa\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6960 - loss: 0.7481 
Loss: 0.7544, Mean Squared Error: 0.6879
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [24]:
y_predNN

array([2, 3, 3, 2, 1, 2, 2, 1, 3, 2, 1, 3, 2, 2, 1, 2, 3, 3, 1, 2, 1, 3,
       2, 1, 3, 1, 2, 1, 1, 1, 2, 3, 1, 2, 3, 2, 3, 3, 2, 3, 3, 2, 2, 3,
       3, 3, 3, 3, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 3, 1, 2, 2, 3, 1, 1, 3,
       3, 1, 3, 1, 3, 1, 3, 1, 2, 3, 3, 2, 1, 3, 3, 1, 3, 1, 3, 1, 2, 2,
       3, 2, 3, 3, 2, 2, 3, 2, 3, 1, 1, 1, 2, 3, 1, 1, 1, 3, 2, 2, 2, 2,
       1, 1, 3, 3, 1, 3, 1, 3, 3, 3, 1, 3, 1, 2, 2, 2, 3, 1, 2, 1, 1, 2,
       3, 1, 3, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 3, 2, 1, 3, 2, 3, 2, 2, 1,
       3, 1, 3, 3, 1, 3, 1, 2, 1, 1, 3, 2, 3, 1, 2, 2, 3, 3, 3, 3, 1, 2,
       2, 1, 2, 1, 3, 1, 3, 3, 1, 3, 3, 1, 1, 2, 3, 1, 1, 1, 2, 3, 2, 2,
       3, 2, 1, 2, 2, 3, 1, 3, 2, 2, 2, 1, 1, 3, 2, 1, 3, 1, 2, 1, 1, 1,
       1, 2, 1, 2, 3, 3, 3, 2, 1, 3, 2, 2, 2, 3, 3, 1, 2, 3, 3, 1, 3, 2,
       3, 3, 3, 1, 1, 1, 2, 1, 1, 1, 2, 3, 1, 3, 3, 1, 1, 1, 2, 2, 1, 2,
       2, 3, 2, 1, 1, 1, 2, 2, 1, 3, 1, 1, 2, 3, 3, 3, 3, 2, 3, 1, 2, 3,
       2, 3, 1, 1, 3, 1, 1, 1, 3, 2, 2, 1, 1, 3, 3,

In [25]:
y_val

array([3, 2, 3, 2, 1, 2, 2, 1, 2, 3, 2, 3, 2, 2, 1, 2, 3, 2, 1, 2, 1, 3,
       2, 1, 3, 1, 1, 2, 1, 1, 2, 3, 1, 2, 3, 2, 2, 3, 2, 2, 2, 2, 3, 2,
       3, 3, 3, 3, 3, 1, 1, 2, 3, 3, 3, 1, 1, 2, 3, 2, 2, 3, 3, 1, 1, 3,
       3, 1, 2, 3, 3, 1, 3, 1, 3, 3, 1, 1, 1, 2, 3, 2, 3, 1, 2, 1, 2, 2,
       3, 1, 2, 3, 1, 2, 2, 2, 2, 1, 1, 2, 2, 3, 1, 1, 1, 2, 2, 2, 2, 3,
       1, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 3, 1, 2, 1, 3, 3, 1, 2, 2, 2, 2,
       3, 1, 2, 2, 1, 2, 1, 3, 1, 1, 2, 2, 2, 1, 2, 1, 3, 2, 3, 2, 2, 1,
       2, 1, 3, 3, 1, 3, 1, 3, 1, 2, 3, 2, 3, 1, 2, 2, 3, 3, 2, 3, 1, 3,
       3, 1, 2, 3, 2, 3, 3, 2, 3, 2, 2, 1, 1, 2, 3, 1, 1, 1, 2, 3, 2, 2,
       2, 2, 1, 1, 3, 3, 3, 3, 1, 3, 2, 1, 1, 3, 1, 2, 2, 1, 3, 1, 1, 2,
       1, 3, 1, 2, 3, 3, 3, 2, 1, 3, 3, 2, 1, 3, 3, 1, 2, 2, 3, 2, 3, 2,
       3, 3, 3, 2, 3, 1, 3, 1, 1, 1, 3, 3, 1, 3, 3, 1, 1, 1, 3, 1, 1, 2,
       2, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 3, 3, 3, 3, 2, 3, 1, 2, 3,
       2, 3, 1, 1, 3, 1, 2, 1, 2, 1, 2, 1, 3, 3, 3,

In [26]:
y_val.sum()

632

In [27]:
y_predNN.sum()

621

### Testando com os dados do professor

In [28]:
import pandas as pd
import requests

#realizando previsões com o arquivo de
print(' - Aplicando modelo para enviando para o servidor')
df = pd.read_csv('abalone_app.csv')

 - Aplicando modelo para enviando para o servidor


In [29]:
# df.pop('sex')
# print("Removido!")

df.loc[(df['sex'] == 'M'), 'sex'] = 2
df.loc[(df['sex'] == 'F'), 'sex'] = 1
df.loc[(df['sex'] == 'I'), 'sex'] = 0

print("Modificado!")

Modificado!


In [30]:
df = scalar.fit_transform(df)

In [31]:
y_pred = model.predict(df)

33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step


In [32]:
# y_pred_classes = np.argmax(y_pred, axis=1)
# y_pred_classes

In [33]:
y_pred = np.argmax(y_pred, axis=1)

In [34]:
y_pred[:100]

array([3, 2, 2, 3, 3, 1, 1, 2, 3, 3, 3, 3, 3, 1, 1, 3, 2, 1, 3, 3, 1, 2,
       1, 2, 3, 2, 2, 3, 3, 3, 3, 2, 1, 3, 2, 2, 2, 3, 2, 2, 1, 3, 3, 3,
       3, 3, 3, 3, 2, 1, 2, 3, 3, 3, 2, 3, 3, 1, 1, 1, 3, 3, 3, 3, 2, 1,
       2, 3, 3, 1, 2, 3, 1, 1, 1, 1, 1, 2, 1, 1, 3, 3, 2, 2, 2, 3, 2, 1,
       2, 3, 3, 1, 3, 1, 2, 2, 3, 2, 3, 1], dtype=int64)

In [35]:
# Enviando previsões realizadas com o modelo para o servidor
URL = "https://aydanomachado.com/mlclass/03_Validation.php"

DEV_KEY = "Set fire in the Machine"

# json para ser enviado para o servidor
data = {'dev_key':DEV_KEY,
        'predictions':pd.Series(y_pred).to_json(orient='values')}

# Enviando requisição e salvando o objeto resposta
r = requests.post(url = URL, data = data)

# Extraindo e imprimindo o texto da resposta
pastebin_url = r.text
print(" - Resposta do servidor:\n", r.text, "\n")

 - Resposta do servidor:
 {"status":"success","dev_key":"Set fire in the Machine","accuracy":0.6593301435406699,"old_accuracy":0.65933014354067} 

